/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ProjectIndexLazyImport = createFileRoute('/project/')()
const ProjectIdIndexLazyImport = createFileRoute('/project/$id/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectIndexLazyRoute = ProjectIndexLazyImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/project/index.lazy').then((d) => d.Route))

const ProjectIdIndexLazyRoute = ProjectIdIndexLazyImport.update({
  id: '/project/$id/',
  path: '/project/$id/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/project/$id/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/$id/': {
      id: '/project/$id/'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/project': typeof ProjectIndexLazyRoute
  '/project/$id': typeof ProjectIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/project': typeof ProjectIndexLazyRoute
  '/project/$id': typeof ProjectIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/project/': typeof ProjectIndexLazyRoute
  '/project/$id/': typeof ProjectIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/project' | '/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/project' | '/project/$id'
  id: '__root__' | '/' | '/about' | '/project/' | '/project/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ProjectIndexLazyRoute: typeof ProjectIndexLazyRoute
  ProjectIdIndexLazyRoute: typeof ProjectIdIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ProjectIndexLazyRoute: ProjectIndexLazyRoute,
  ProjectIdIndexLazyRoute: ProjectIdIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/project/",
        "/project/$id/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/project/": {
      "filePath": "project/index.lazy.tsx"
    },
    "/project/$id/": {
      "filePath": "project/$id/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
